packages:
  - '.'
allowBuilds:
  '@parcel/watcher': true
  es5-ext: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@marschat/auth-components'
  - '@marschat/frontend-common'
onlyBuiltDependencies:
  - esbuild
  - "@parcel/watcher"
  - es5-ext
  - vue-demi
