[package]
name = "qr_code_tool"
version = "1.0.0"
edition = "2021"

[dependencies]
iced = { version = "0.13", features = ["tiny-skia", "image", "svg"] }
qrcodegen = "1.8"
rqrr = "0.9"
brotli = "7"
base45 = "3"
flate2 = "1"
image = "0.25"
base64 = "0.22"
anyhow = "1"
chrono = "0.4"
rfd = "0.15"

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
]

[build-dependencies]
image = "0.25"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
opt-level = "z"
panic = "abort"
