spring:
  datasource:
    url: jdbc:mysql://192.168.31.182:3306/kb_auth?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: kb
    password: kb123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      keepalive-time: 60000
      connection-timeout: 5000
  data:
    redis:
      host: 192.168.31.182
      port: 6379
      database: 0
      timeout: 5000ms
