# 端口号，每个实例要不同
port 7001

# 启用集群模式，这是关键！
cluster-enabled yes

# 集群配置文件，由 Redis 自动生成和维护，你只需指定名称
cluster-config-file nodes-7001.conf

# 集群节点超时时间
cluster-node-timeout 5000

# 附加模式，如果为 yes，则日志会在前台显示，如果为 no，则作为服务运行在后台
appendonly yes

# 如果你不需要持久化，可以设置为 no，但学习时不建议关闭
# save ""

# 启用保护模式
protected-mode yes

# 设置认证密码
requirepass test@123

# 设置集群节点间通信的密码（必须与requirepass一致）
masterauth test@123

daemonize yes

# 允许远程连接（重要！）
bind 0.0.0.0

# 设置集群节点通信IP（重要！）
# 将127.0.0.1改为你的服务器IP或域名
cluster-announce-ip 172.22.38.94

# 客户端访问端口，处理数据读写请求	通常可不设（使用默认）
# cluster-announce-port 7001

# 节点间内部通信端口，用于集群管理	必须配置且唯一
cluster-announce-bus-port 17001