packages:
  - '.'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
onlyBuiltDependencies:
  - esbuild
  - "@parcel/watcher"
minimumReleaseAgeExclude:
  - '@marschat/auth-components'
  - '@marschat/frontend-common'
